package io.pleo.antaeus.models

enum class BillProcessorFlowState {
    START_STATE,
    VALIDATE_MAXIMUM_NUMBER_RETRIES_EXCEEDED_STATE,
    MAXIMUM_NUMBER_RETRIES_EXCEEDED_STATE,
    MAXIMUM_NUMBER_RETRIES_NOT_EXCEEDED_STATE,

    QUERY_QUEUE_STATUS_STATE,

    INVOKE_PAYMENT_PROVIDER_STATE,
    PAYMENT_SUCCESSFUL_STATE,
    PAYMENT_UNSUCCESSFUL_STATE,
    EXCEPTION_ENCOUNTERED_STATE,

    STOP_STATE
}
